import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css';
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <div>
        <h2>Next.js Assignment-1</h2>
        <div className="parent-button">
        <Link href="/Assignment-5/question-1">
          <button>Question-1</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-2">
          <button>Question-2</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-3">
          <button>Question-3</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-4">
          <button>Question-4</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-5">
          <button>Question-5</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-6">
          <button>Question-6</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-7">
          <button>Question-7</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-8">
          <button>Question-8</button>
        </Link>{"  "}
        <Link href="/Assignment-5/question-9">
          <button>Question-9</button>
        </Link>{"  "}
           <Link href="/Assignment-5/question-10">
          <button>Question-10</button>
        </Link>{"  "}
           <Link href="/Assignment-5/question-11">
          <button>Question-11</button>
        </Link>{"  "}
           <Link href="/Assignment-5/question-12">
          <button>Question-12</button>
        </Link>{"  "}
           <Link href="/Assignment-5/question-13">
          <button>Question-13</button>
        </Link>{"  "}
       </div>

        {children}
        </div>
  
       
  );
}
