import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ThemeSwitcher } from "@/components";
import ThemeProvider from "@/context/ThemeContext";
import LanguageProvider from "@/context/LanguageContext";
import { AuthContextProvider } from "@/context/AuthContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <ThemeProvider>
        <body style={bodyStyle}>
          {/* Sidebar */}
          <aside style={sidebarStyle}>
            <h2 style={{ fontSize: "22px", marginBottom: "20px" }}>Assignments</h2>
            <nav style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
              <Link href="/" style={linkStyle}>Home</Link>
              <Link href="/Assignment-1" style={linkStyle}>Assignment 1</Link> 
              <Link href="/Assignment-2" style={linkStyle}>Assignment 2</Link>
              <Link href="/Assignment-3" style={linkStyle}>Assignment-3</Link>
            </nav>
          </aside>

          {/* Main content */}
          <main style={mainContentStyle}>
            <ThemeSwitcher />
            <LanguageProvider>
              <AuthContextProvider>
              {children}
              </AuthContextProvider>
            </LanguageProvider>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
};
const bodyStyle = {
  display: "flex",
  minHeight: "100vh",
  margin: 0,
};
const sidebarStyle = {
  width: "240px",
  backgroundColor: "#1e293b", 
  color: "white",
  padding: "20px",
  display: "flex",
  flexDirection: "column",
};

const linkStyle = {
  color: "white",
  padding: "10px 16px",
  border: "none",
  borderRadius: "6px",
  textAlign: "left",
  fontWeight: "500",
  cursor: "pointer",
  textDecoration: "none",
};

const mainContentStyle = {
  flex: 1,
  padding: "40px",
};

export default RootLayout;
