import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import { AuthContextProvider } from "@/context/AuthContext";
import { ThemeSwitcher } from "@/components";
import ThemeProvider from "@/context/ThemeContext";
import LanguageProvider from "@/context/LanguageContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body style={{ display: "flex", minHeight: "100vh" }}>
        {/* Sidebar */}
        <aside style={sidebarStyle}>
          <h2 style={{ fontSize: "22px", marginBottom: "20px" }}>Assignments</h2>
          <nav style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <Link href="/" style={linkStyle}>Home</Link>
            <Link href="/Assignment-1" style={linkStyle}>Assignment 1</Link>
            <Link href="/Assignment-2" style={linkStyle}>Assignment 2</Link>
            <Link href="/Assignment-3" style={linkStyle}>Assignment 3</Link>
            <Link href="/Assignment-4" style={linkStyle}>Assignment 4</Link>
            <Link href="/Assignment-5" style={linkStyle}>Assignment 5</Link>
            <Link href="/Assignment-6" style={linkStyle}>Assignment 6</Link>

            <hr style={{ margin: "20px 0" }} />

            <Link href="/about" style={linkStyle}>About</Link>
            <Link href="/dashboard" style={linkStyle}>Dashboard</Link>
            <Link href="/profile" style={linkStyle}>Profile</Link>
            <Link href="/settings" style={linkStyle}>Settings</Link>
          </nav>
        </aside>

        {/* Main content */}
        <main style={mainContentStyle}>
          <ThemeProvider>
            <ThemeSwitcher />
            <LanguageProvider>
              <AuthContextProvider>{children}</AuthContextProvider>
            </LanguageProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
};

const sidebarStyle = {
  width: "240px",
  backgroundColor: "#1e293b",
  color: "white",
  padding: "20px",
  display: "flex",
  flexDirection: "column",
};

const linkStyle = {
  backgroundColor: "#3b82f6",
  color: "white",
  padding: "10px 16px",
  border: "none",
  borderRadius: "6px",
  textAlign: "left",
  fontWeight: "500",
  cursor: "pointer",
  textDecoration: "none",
};

const mainContentStyle = {
  flex: 1,
  padding: "40px",
  backgroundColor: "#f4f6f8",
};

export default RootLayout;
