import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
        <h2>Next.js Assignment-1</h2>
        <div className="parent-button">
        <Link href="/assignment-1/question-1">
          <button>Question-1</button>
        </Link>{"  "}
        <Link href="/assignment-1/question-2">
          <button>Question-2</button>
        </Link>{"  "}
        <Link href="/assignment-1/question-3">
          <button>Question-3</button>
        </Link>{"  "}
        <Link href="/assignment-1/question-4">
          <button>Question-4</button>
        </Link>{"  "}
        <Link href="/assignment-1/question-5">
          <button>Question-5</button>
        </Link>{"  "}
        <Link href="/assignment-1/question-6">
          <button>Question-6</button>
        </Link>{"  "}
       </div>
        </div>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        </body>
    </html>
  );
}
